<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Label="Configuration">
    <OutDir>$(SolutionDir)build\$(Platform)-$(Configuration)\$(MSBuildProjectName)\</OutDir>
    <IntDir>$(SolutionDir)build\intermediate\$(Platform)-$(Configuration)\$(MSBuildProjectName)\</IntDir>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <WarningLevel>Level4</WarningLevel>
      <PreprocessorDefinitions>WIN32_LEAN_AND_MEAN;WINRT_LEAN_AND_MEAN;NOGDICAPMASKS;NORASTEROPS;NODRAWTEXT;NOKERNEL;NOMEMMGR;NOMINMAX;NOOPENFILE;NOSCROLL;NOSERVICE;NOSOUND;NOKANJI;NOHELP;NOPROFILER;NOMCX;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <FloatingPointModel>Fast</FloatingPointModel>
      <LanguageStandard Condition="'$(VisualStudioVersion)'&gt;='18.0'">stdcpp23</LanguageStandard>
      <LanguageStandard Condition="'$(VisualStudioVersion)'&lt; '18.0'">stdcpplatest</LanguageStandard>
      <IntrinsicFunctions>true</IntrinsicFunctions>
      <TreatSpecificWarningsAsErrors>4062;4244;4263;4264;4311;4312;4640;4826;4905;4906</TreatSpecificWarningsAsErrors>
      <AdditionalOptions>/utf-8 %(AdditionalOptions)</AdditionalOptions>
    </ClCompile>
  </ItemDefinitionGroup>
  <ItemDefinitionGroup Condition="'$(Configuration)'=='Debug'">
    <ClCompile>
      <PreprocessorDefinitions>_DEBUG;%(PreprocessorDefinitions)</PreprocessorDefinitions>
    </ClCompile>
  </ItemDefinitionGroup>
  <ItemDefinitionGroup Condition="'$(Configuration)'=='Release'">
    <ClCompile>
      <FavorSizeOrSpeed>Speed</FavorSizeOrSpeed>
      <PreprocessorDefinitions>NDEBUG;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <ControlFlowGuard>Guard</ControlFlowGuard>
    </ClCompile>
  </ItemDefinitionGroup>
  <ItemDefinitionGroup Condition="'$(Platform)'=='Win32'">
    <ClCompile>
      <EnableEnhancedInstructionSet>StreamingSIMDExtensions2</EnableEnhancedInstructionSet>
    </ClCompile>
  </ItemDefinitionGroup>
  <ItemDefinitionGroup Condition="'$(Platform)'=='x64'">
    <ClCompile>
      <OmitFramePointers>true</OmitFramePointers>
      <EnableEnhancedInstructionSet>AdvancedVectorExtensions2</EnableEnhancedInstructionSet>
    </ClCompile>
  </ItemDefinitionGroup>
</Project>