<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Label="Configuration">
    <OutDir>$(SolutionDir)build\$(Platform)-$(Configuration)\$(MSBuildProjectName)\</OutDir>
    <IntDir>$(SolutionDir)build\intermediate\$(Platform)-$(Configuration)\$(MSBuildProjectName)\</IntDir>
  </PropertyGroup>
  <PropertyGroup Label="Versioning">
    <RoxygVersionMajor>0</RoxygVersionMajor>
    <RoxygVersionMinor>1</RoxygVersionMinor>
    <RoxygVersionPatch>0</RoxygVersionPatch>
    <RoxygVersionBuild Condition="$(RoxygVersionBuild)==''">$([System.DateTime]::Now.ToString(`yyyy`))</RoxygVersionBuild>
    <RoxygVersionRevision Condition="$(RoxygVersionRevision)==''">$([System.DateTime]::Now.ToString(`MMdd`))</RoxygVersionRevision>
    <RoxygVersionPreRelease>alpha</RoxygVersionPreRelease>
    <RoxygVersionPreReleaseId Condition="'$(RoxygVersionPreReleaseId)'=='' and '$(RoxygVersionPreRelease)'=='alpha'">0</RoxygVersionPreReleaseId>
    <RoxygVersionPreReleaseId Condition="'$(RoxygVersionPreReleaseId)'=='' and '$(RoxygVersionPreRelease.StartsWith(`alpha`))'">$(RoxygVersionPreRelease.Substring(5))</RoxygVersionPreReleaseId>
    <RoxygVersionPreReleaseId Condition="'$(RoxygVersionPreReleaseId)'=='' and '$(RoxygVersionPreRelease)'=='beta'">50</RoxygVersionPreReleaseId>
    <RoxygVersionPreReleaseId Condition="'$(RoxygVersionPreReleaseId)'=='' and '$(RoxygVersionPreRelease.StartsWith(`beta`))'">$([MSBuild]::Add(50, $([System.Convert]::ToUInt16($(RoxygVersionPreRelease.Substring(4)), 10))))</RoxygVersionPreReleaseId>
    <RoxygVersionPreReleaseId Condition="'$(RoxygVersionPreReleaseId)'==''">100</RoxygVersionPreReleaseId>
    <RoxygFileVersion>$(RoxygVersionMajor).$(RoxygVersionMinor).$(RoxygVersionBuild).$(RoxygVersionRevision)</RoxygFileVersion>
    <RoxygFileVersionShort>$(RoxygVersionMajor).$(RoxygVersionMinor)</RoxygFileVersionShort>
    <RoxygProductVersion Condition="'$(RoxygVersionPreReleaseId)'&lt; '100'">$(RoxygVersionMajor).$(RoxygVersionMinor).$(RoxygVersionPatch)-$(RoxygVersionPreRelease)</RoxygProductVersion>
    <RoxygProductVersion Condition="'$(RoxygVersionPreReleaseId)'&gt;='100'">$(RoxygVersionMajor).$(RoxygVersionMinor).$(RoxygVersionPatch)</RoxygProductVersion>
    <RoxygPreprocessorDefinitions>ROXYG_VER_FILE_VERSION=$(RoxygVersionMajor),$(RoxygVersionMinor),$(RoxygVersionBuild),$(RoxygVersionRevision);ROXYG_VER_FILE_VERSION_STRING=$(RoxygFileVersion);ROXYG_VER_PRODUCT_VERSION=$(RoxygVersionMajor),$(RoxygVersionMinor),$(RoxygVersionPatch),$(RoxygVersionPreReleaseId);ROXYG_VER_PRODUCT_VERSION_STRING=$(RoxygProductVersion)</RoxygPreprocessorDefinitions>
  </PropertyGroup>
  <ItemDefinitionGroup Label="Versioning">
    <ClCompile>
      <PreprocessorDefinitions>$(RoxygPreprocessorDefinitions);%(PreprocessorDefinitions)</PreprocessorDefinitions>
    </ClCompile>
    <Link>
      <MinimumRequiredVersion>10.0</MinimumRequiredVersion>
      <Version>$(RoxygFileVersionShort)</Version>
      <AdditionalOptions>/OSVERSION:10.0 %(AdditionalOptions)</AdditionalOptions>
    </Link>
    <ResourceCompile>
      <PreprocessorDefinitions>$(RoxygPreprocessorDefinitions);%(PreprocessorDefinitions)</PreprocessorDefinitions>
    </ResourceCompile>
  </ItemDefinitionGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <WarningLevel>Level4</WarningLevel>
      <PreprocessorDefinitions>WIN32_LEAN_AND_MEAN;WINRT_LEAN_AND_MEAN;NOGDICAPMASKS;NORASTEROPS;NODRAWTEXT;NOKERNEL;NOMEMMGR;NOMINMAX;NOOPENFILE;NOSCROLL;NOSERVICE;NOSOUND;NOKANJI;NOHELP;NOPROFILER;NOMCX;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <FloatingPointModel>Fast</FloatingPointModel>
      <LanguageStandard Condition="'$(VisualStudioVersion)'&gt;='18.0'">stdcpp23</LanguageStandard>
      <LanguageStandard Condition="'$(VisualStudioVersion)'&lt; '18.0'">stdcpplatest</LanguageStandard>
      <IntrinsicFunctions>true</IntrinsicFunctions>
      <TreatSpecificWarningsAsErrors>4062;4244;4263;4264;4311;4312;4640;4826;4905;4906</TreatSpecificWarningsAsErrors>
      <AdditionalOptions>/utf-8 %(AdditionalOptions)</AdditionalOptions>
    </ClCompile>
  </ItemDefinitionGroup>
  <ItemDefinitionGroup Condition="'$(Configuration)'=='Debug'">
    <ClCompile>
      <PreprocessorDefinitions>_DEBUG;%(PreprocessorDefinitions)</PreprocessorDefinitions>
    </ClCompile>
  </ItemDefinitionGroup>
  <ItemDefinitionGroup Condition="'$(Configuration)'=='Release'">
    <ClCompile>
      <FavorSizeOrSpeed>Speed</FavorSizeOrSpeed>
      <PreprocessorDefinitions>NDEBUG;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <ControlFlowGuard>Guard</ControlFlowGuard>
    </ClCompile>
  </ItemDefinitionGroup>
  <ItemDefinitionGroup Condition="'$(Platform)'=='Win32'">
    <ClCompile>
      <EnableEnhancedInstructionSet>StreamingSIMDExtensions2</EnableEnhancedInstructionSet>
    </ClCompile>
  </ItemDefinitionGroup>
  <ItemDefinitionGroup Condition="'$(Platform)'=='x64'">
    <ClCompile>
      <OmitFramePointers>true</OmitFramePointers>
      <EnableEnhancedInstructionSet>AdvancedVectorExtensions2</EnableEnhancedInstructionSet>
    </ClCompile>
  </ItemDefinitionGroup>
</Project>